version: '3.9'
services:
  # Client
  client:
    container_name: client_container
    build: ./frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - mongo
      - server
    volumes:
      - ./frontend:/user/src/app
      - /user/src/app/node_modules
  # Server
  server:
    container_name: server_container
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/user/src/app
      - /user/src/app/node_modules
  # MOngoDB
  mongo:
    container_name: mongo_container
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
