version: '3.9'
services:
  # Client
  client:
    container_name: client_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
    networks:
      - emazona-mearn
    depends_on:
      - mongo
      - server
    volumes:
      - ./frontend:/user/src/app
      - /user/src/app/node_modules
  # Server
  server:
    container_name: server_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    networks:
      - emazona-mearn
    depends_on:
      - mongo

    volumes:
      - ./backend:/user/src/app
      - /user/src/app/node_modules
  # MOngoDB
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - ./DB/.env
    networks:
      - emazona-mearn
    volumes:
      - mongo_db:/data/db

networks:
  emazona-mearn:
    driver: bridge
volumes:
  mongo_db:
    external: true
