FROM node:16.17.1-alpine3.15
RUN addgroup -S app && adduser -S app -G app

USER app

WORKDIR /user/src/app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .
ENV PORT 5000
EXPOSE ${PORT}

CMD ["npm","start"]
