name: Node CI
on:
  - pull_request
  - push

jobs:
  frontend:
    name: Frontend Task
    runs-on: ubuntu-latest
    # needs: backend
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0
      - name: Install Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Frontend Dependance
        run: |
          cd backend         
          yarn install --frozen-lockfile
      - name: Run Test
        run: |
          cd backend
          yarn test
          node -v

  sample:
    runs-on: ubuntu-latest
    steps:
      - run: ls
