name: Node CI
on:
  - pull_request
  - push

jobs:
  frontend:
    name: Frontend Task
    runs-on: ubuntu-latest
    needs: backend
    steps:
      
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0

      - name: Install Frontend Dependance
        run: |         
          cd frontend         
          yarn install --frozen-lockfile      
      - name: Run Tast
        run: |
          cd frontend
          yarn test

  backend:
    name: Backend Task
    runs-on: ubuntu-latest
    steps:
      - name: Node Version
        run: |
          node -v
          npm -v
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt install nodejs
          node -v
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0
      
      - name: Install Backend Dependance
        run: |
          cd backend
          yarn install --frozen-lockfile
          ls
