name: Node CI
on:
  - pull_request
  - push

jobs:
  frontend:
    name: Frontend Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0

      - name: Install Frontend Dependance
        run: |         
          cd frontend         
          yarn install --frozen---frozen-lockfile      
      - name: Run Tast
        run: |
          cd frontend
          yarn test
