name: Node CI
on:
  - pull_request
  - push

jobs:
  frontend:
    name: Frontend Task
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0
      - name: Install Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Frontend Dependance
        run: |
          cd frontend         
          yarn install --frozen-lockfile
      - name: Run Test
        run: |
          cd frontend
          yarn test
          node -v

  backend:
    name: Backend Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2.5.0
      - name: Install Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Start MongoDb
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
      - name: Install Backend Dependance
        run: |
          cd backend &&
          yarn install --frozen-lockfile &&
          ls
      - name: Run Backend Test
        run: |
          cd backend &&
          yarn dev &&
          yarn test
          node -v
